/*
 *  TINY0.h
 *  Author: Nikola Kirov
 */
#ifndef TINY0_H_
#define TINY0_H_
	
	#define AVR0_VERSION				001
	
	#include "Common_cfg.h"

	// Atmel start configuration
#ifdef ASTART_PROJECT	
	#include <compiler.h>
#endif

#ifdef MCC_PROJECT	
	#include "../mcc_generated_files/system/clock.h"
#endif
	
	#include <AVR0_cfg.h>

#ifdef ASTART_PROJECT	
	// generated by atmel start
	#include "clock_config.h"
#endif	
	
	#include ".\AVR\cycle_counter_avr.h"	
	#include ".\AVR\AVR_common.h"	
	
	#include "AVR0_Macro.h"
	#include "AVR0_Utility.h"
	#include ".\AVR\SimpleUsart.h"
	#include ".\AVR\SimpleUsart1.h"
	#include ".\AVR\SimpleUsart2.h"

#ifdef __cplusplus
	extern "C" {
#endif

	//================================================ Peripheral libs
	#include "AVR0_EEprom.h"
	//#include "SimpleUsart.h"
	//#include "SPIM.h"

/*************** API ************************/	
		/* Init library */
	void AVR0_init(void);
	
#ifdef __cplusplus
}
#endif
	
#endif /* AVR3_H_ */
